### ISSUE TITLE
How to use only Pull Refresh

### ISSUE THREAD

**Issue by vukhacbiet** [YvesCoding/vuescroll#202]
I only want to use Pull to Refresh and don't need a custom scrollbar, infinity load.

Please tell me how I could do it?

**Comment by wangyi7099** [comment]
// To disable push load
{
 pushLoad: {
  enable: false,
}
}

Currently there is no internal option to use native bar.
You can do it by css override:
```css
.__panel {
  height:100%!important;
margin-right:0!important;
}
```
