### ISSUE TITLE
touch scroll not working with transform rotate

### ISSUE THREAD

**Issue by brnteka** [YvesCoding/vuescroll#245]
Hello, thank you for your plugin, but we run into an issue with it, it seems that touch scroll stops working when transform: rotate is applied to the parent element, Demo: https://codepen.io/mpbrainwave/pen/PoWYRaY with desktop it works just fine, but not with mobile devices, is there any workaround for this issue?

**Comment by wangyi7099** [comment]
add this style for the element which is rotated
```css
      .__panel {
        overflow: scroll !important;
      }
```
