### ISSUE TITLE
Custom hover Bar style

### ISSUE THREAD

**Issue by avpuchkova** [YvesCoding/vuescroll#250]
How hover Bar can be customized? I use 
`          bar: {
            hoverStyle: true
          },`
But where should be style for hover?

**Comment by wangyi7099** [comment]
Using css to override

**Comment by avpuchkova** [comment]
@wangyi7099 Can you show some example please? This does not work:
`.__bar-is-horizontal:hover {
  background-color: red !important;
}`

**Comment by wangyi7099** [comment]
select bar wrapper rather than bar

**Comment by avpuchkova** [comment]
`.__bar-wrap-is-horizontal:hover {
  background-color: yellow !important;
}`
does not work too

**Comment by blankzz** [comment]
```scss
.__bar-wrap-is-vertical:hover {
    .__bar-is-vertical {
        width: 10px !important;
    }
}
```

Hey，这样设置的话是可行的，需要注意的是需要加 `!important`
